blog/urls.py
from django.urls import path, include, re_path
from blog import views

app_name = 'blog'

urlpatterns = [

    path('', views.index, name='base'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('otp_verify', views.otp_verify, name='otp'),
    path('profile/', views.user_profile, name='profile'),
    path('special/', views.special_fn,name='special'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    re_path(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    #----------------------------------------------------------------------------------
    re_path('^post/published/$', views.PostListView.as_view(),name='post_list'),
    re_path(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    re_path(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    #-----------------------------------------------------------------------------------

     



]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('', include('payments.urls')),
    path('login/', LoginView.as_view(), name='login'),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/register/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Log IN</h1>
<form action="{% url 'blog:login' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="usr"> Username </label>
    <input type="text" id = 'usr' name = 'username'>
    
    <label for="pwd"> Password </label>
    <input type="password" id = 'pwd' name = 'password'>

    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/register/otp_verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'blog:otp' %}" method='POST'>
        {% csrf_token %}
        <label for="otp"></label>
        <input type="text" id="otp" name = "cnf_otp" placeholder="Enter Otp">
        <input type="hidden" name= 'otp' value={{otp}}>
        <input type="hidden" name= 'username' value={{username}}>
        <input type="submit" value="Confirm Otp">
    </form>
</body>
</html>

templates/register/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'blog:profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit"  value="Submit">
    </form>
</body>
</html>

templates/register/reg.html
{% extends 'base.html' %}

{% block content %}
<h1>Registration</h1>
<form action="{% url 'blog:register' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {{user.as_p}}
    {{profile.as_p}}

    <input type="submit" value="Submit">
</form>
{% endblock %}