blog/urls.py
from django.urls import path, include, re_path
from blog import views

app_name = 'blog'

urlpatterns = [

    path('', views.index, name='base'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('otp_verify', views.otp_verify, name='otp'),
    path('profile/', views.user_profile, name='profile'),
    path('special/', views.special_fn,name='special'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    re_path(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    #----------------------------------------------------------------------------------
    re_path('^post/published/$', views.PostListView.as_view(),name='post_list'),
    re_path(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    re_path(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    #----------------------------------------------------------------------------------
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    #-----------------------------------------------------------------------------------

     



]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import LoginView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blog.urls')),
    path('', include('payments.urls')),
    path('login/', LoginView.as_view(), name='login'),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Daily Blogs</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   <style>
    .jmb{ 
     background-color: bisque; 
     padding: 10px;  
     margin: 15px;
     border: chartreuse solid 5px;
     border-radius: 10px;
    }

    .srch{
        padding: 10px;  
     margin: 5px;
     border: chartreuse solid 5px;
    }
   </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#" title="Know about Us">Daily Blogs</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'blog:base' %}">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Yesterday</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><form class="form-search srch" method="get" id="s" action="/">
        <div class="input-append">
            <input type="text" class="input-medium search-query" name="s" placeholder="Keywords Here" value="">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span> Search
              </button>
        </div>
    </form></li>
    </ul> 
    <ul class="nav navbar-nav navbar-right"> 
        {% if request.session.user_login %}
        li><a href="{% url 'blog:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
      <li><a href="{% url 'blog:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'blog:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
    </ul>
  </div>
</nav>

<div class="container">
    
    <div class="jumbtron jmb">
        {% block content%}
        {% endblock %}
    </div>
</div>
    
</body>
</html>